### ISSUE TITLE
Formatting of Page Links

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#506]
I'm noticing two formatting things we might want to fix:

1. The end of the "next page" is ending up on a second line (I'm not sure if this is already in another ticket? I'm not finding it.
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/5f3480a3-d041-4117-ac4e-2fa6f8cba48f)

2. On some pages, the bottom pagination widget is fine https://digital.library.emory.edu/?page=1201&q=&search_field=common_fields 
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/1eb61c3b-5e2c-40b9-b3ac-0cb4caa715f1)

But on others, it also breaks to a second line, which looks odd https://digital.library.emory.edu/?page=1199&q=&search_field=common_fields 
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/d2dd9b77-01af-410b-9ab1-c0e6a5b46ea8)

**Comment by nikdragovic** [comment]
Thanks @maxkadel. That does look odd and we should fix it at some point.

**Comment by maxkadel** [comment]
before
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/6920c76e-4e45-4ed8-ac5c-7026e0ab221c)

after
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/7647052f-c7b5-4cb4-afb2-361f3387d690)

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/5dcc8dd8-8920-4982-819f-c3ec290e5680)

**Comment by maxkadel** [comment]
Aligned pagination widget to search results, so that when there are many search results, the widget will still show on a single line ![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/bca6d30f-cb56-4a0b-9f63-33038507a238)
